[project]
name = "keep-it-secret"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "pydantic-settings>=2.11.0",
    "structlog>=25.4.0",
    "uvicorn>=0.35.0",
]
